var gods = [{
    "name": "Agni",
    "data": {
        "stages": ["mid"],
        "damageType": "magical",
        "meta": 3.5
    },
    "roles": {
        "carry": 1,
        "support": 1,
        "mid": 5,
        "jungle": 2,
        "solo": 1
    },
    "matchups": [{
        "god": "Agni",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Anubis",
        "against": 50,
        "teammate": 20
    }, {
        "god": "Arachne",
        "against": 75,
        "teammate": 55
    }, {
        "god": "Artemis",
        "against": 60,
        "teammate": 50
    }, {
        "god": "Bastet",
        "against": 40,
        "teammate": 60
    }, {
        "god": "Hades",
        "against": 55,
        "teammate": 45
    }, {
        "god": "He Bo",
        "against": 55,
        "teammate": 35
    }, {
        "god": "Hel",
        "against": 50,
        "teammate": 60
    }, {
        "god": "Hun Batz",
        "against": 30,
        "teammate": 60
    }, {
        "god": "Kali",
        "against": 50,
        "teammate": 55
    }, {
        "god": "Kukulcan",
        "against": 50,
        "teammate": 20
    }, {
        "god": "Odin",
        "against": 30,
        "teammate": 55
    }, {
        "god": "Ra",
        "against": 40,
        "teammate": 30
    }, {
        "god": "Sobek",
        "against": 30,
        "teammate": 60
    }, {
        "god": "Vamana",
        "against": 25,
        "teammate": 55
    }, {
        "god": "Ymir",
        "against": 40,
        "teammate": 50
    }, {
        "god": "Zeus",
        "against": 60,
        "teammate": 30
    }, {
        "god": "Bakasura",
        "against": 50,
        "teammate": 60
    }, {
        "god": "Anhur",
        "against": 30,
        "teammate": 60
    }, {
        "god": "Cupid",
        "against": 40,
        "teammate": 60
    }, {
        "god": "Thor",
        "against": 35,
        "teammate": 60
    }, {
        "god": "Ares",
        "against": 35,
        "teammate": 55
    }, {
        "god": "Freya",
        "against": 70,
        "teammate": 60
    }, {
        "god": "Loki",
        "against": 40,
        "teammate": 50
    }, {
        "god": "Bacchus",
        "against": 45,
        "teammate": 40
    }, {
        "god": "Xbalanque",
        "against": 45,
        "teammate": 50
    }]
}, {
    "name": "Anubis",
    "data": {
        "stages": ["early", "mid", "late"],
        "damageType": "magical",
        "meta": 2
    },
    "roles": {
        "carry": 1,
        "support": 1,
        "mid": 5,
        "jungle": 3,
        "solo": 2
    },
    "matchups": [{
        "god": "Agni",
        "against": 50,
        "teammate": 20
    }, {
        "god": "Anubis",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Arachne",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Artemis",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Bastet",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Hades",
        "against": 50,
        "teammate": 50
    }, {
        "god": "He Bo",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Hel",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Hun Batz",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Kali",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Kukulcan",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Odin",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Ra",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Sobek",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Vamana",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Ymir",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Zeus",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Bakasura",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Anhur",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Cupid",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Thor",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Ares",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Freya",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Loki",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Bacchus",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Xbalanque",
        "against": 50,
        "teammate": 50
    }]
}, {
    "name": "Arachne",
    "data": {
        "stages": ["early", "mid", "late"],
        "damageType": "magical",
        "meta": 2.5
    },
    "roles": {
        "carry": 1,
        "support": 1,
        "mid": 1,
        "jungle": 5,
        "solo": 3
    },
    "matchups": [{
        "god": "Agni",
        "against": 25,
        "teammate": 55
    }, {
        "god": "Anubis",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Arachne",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Artemis",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Bastet",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Hades",
        "against": 50,
        "teammate": 50
    }, {
        "god": "He Bo",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Hel",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Hun Batz",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Kali",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Kukulcan",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Odin",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Ra",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Sobek",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Vamana",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Ymir",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Zeus",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Bakasura",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Anhur",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Cupid",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Thor",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Ares",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Freya",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Loki",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Bacchus",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Xbalanque",
        "against": 50,
        "teammate": 50
    }]
}, {
    "name": "Artemis",
    "data": {
        "stages": ["early", "mid", "late"],
        "damageType": "magical",
        "meta": 2
    },
    "roles": {
        "carry": 5,
        "support": 1,
        "mid": 2,
        "jungle": 2,
        "solo": 1
    },
    "matchups": [{
        "god": "Agni",
        "against": 40,
        "teammate": 50
    }, {
        "god": "Anubis",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Arachne",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Artemis",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Bastet",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Hades",
        "against": 50,
        "teammate": 50
    }, {
        "god": "He Bo",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Hel",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Hun Batz",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Kali",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Kukulcan",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Odin",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Ra",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Sobek",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Vamana",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Ymir",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Zeus",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Bakasura",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Anhur",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Cupid",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Thor",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Ares",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Freya",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Loki",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Bacchus",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Xbalanque",
        "against": 50,
        "teammate": 50
    }]
}, {
    "name": "Bastet",
    "data": {
        "stages": ["early", "mid", "late"],
        "damageType": "magical",
        "meta": 2.5
    },
    "roles": {
        "carry": 1,
        "support": 1,
        "mid": 1,
        "jungle": 5,
        "solo": 3
    },
    "matchups": [{
        "god": "Agni",
        "against": 60,
        "teammate": 60
    }, {
        "god": "Anubis",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Arachne",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Artemis",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Bastet",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Hades",
        "against": 50,
        "teammate": 50
    }, {
        "god": "He Bo",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Hel",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Hun Batz",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Kali",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Kukulcan",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Odin",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Ra",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Sobek",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Vamana",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Ymir",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Zeus",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Bakasura",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Anhur",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Cupid",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Thor",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Ares",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Freya",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Loki",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Bacchus",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Xbalanque",
        "against": 50,
        "teammate": 50
    }]
}, {
    "name": "Hades",
    "data": {
        "stages": ["early", "mid", "late"],
        "damageType": "magical",
        "meta": 2.5
    },
    "roles": {
        "carry": 1,
        "support": 1,
        "mid": 4,
        "jungle": 1,
        "solo": 4
    },
    "matchups": [{
        "god": "Agni",
        "against": 45,
        "teammate": 45
    }, {
        "god": "Anubis",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Arachne",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Artemis",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Bastet",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Hades",
        "against": 50,
        "teammate": 50
    }, {
        "god": "He Bo",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Hel",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Hun Batz",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Kali",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Kukulcan",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Odin",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Ra",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Sobek",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Vamana",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Ymir",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Zeus",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Bakasura",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Anhur",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Cupid",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Thor",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Ares",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Freya",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Loki",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Bacchus",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Xbalanque",
        "against": 50,
        "teammate": 50
    }]
}, {
    "name": "He Bo",
    "data": {
        "stages": ["early", "mid", "late"],
        "damageType": "magical",
        "meta": 3.5
    },
    "roles": {
        "carry": 3,
        "support": 1,
        "mid": 4,
        "jungle": 4,
        "solo": 3
    },
    "matchups": [{
        "god": "Agni",
        "against": 45,
        "teammate": 35
    }, {
        "god": "Anubis",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Arachne",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Artemis",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Bastet",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Hades",
        "against": 50,
        "teammate": 50
    }, {
        "god": "He Bo",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Hel",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Hun Batz",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Kali",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Kukulcan",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Odin",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Ra",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Sobek",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Vamana",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Ymir",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Zeus",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Bakasura",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Anhur",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Cupid",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Thor",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Ares",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Freya",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Loki",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Bacchus",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Xbalanque",
        "against": 50,
        "teammate": 50
    }]
}, {
    "name": "Hel",
    "data": {
        "stages": ["early", "mid", "late"],
        "damageType": "magical",
        "meta": 3.5
    },
    "roles": {
        "carry": 1,
        "support": 3,
        "mid": 4,
        "jungle": 1,
        "solo": 3
    },
    "matchups": [{
        "god": "Agni",
        "against": 50,
        "teammate": 60
    }, {
        "god": "Anubis",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Arachne",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Artemis",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Bastet",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Hades",
        "against": 50,
        "teammate": 50
    }, {
        "god": "He Bo",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Hel",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Hun Batz",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Kali",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Kukulcan",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Odin",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Ra",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Sobek",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Vamana",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Ymir",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Zeus",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Bakasura",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Anhur",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Cupid",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Thor",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Ares",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Freya",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Loki",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Bacchus",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Xbalanque",
        "against": 50,
        "teammate": 50
    }]
}, {
    "name": "Hun Batz",
    "data": {
        "stages": ["early", "mid", "late"],
        "damageType": "magical",
        "meta": 4
    },
    "roles": {
        "carry": 1,
        "support": 1,
        "mid": 1,
        "jungle": 5,
        "solo": 2.5
    },
    "matchups": [{
        "god": "Agni",
        "against": 70,
        "teammate": 60
    }, {
        "god": "Anubis",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Arachne",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Artemis",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Bastet",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Hades",
        "against": 50,
        "teammate": 50
    }, {
        "god": "He Bo",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Hel",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Hun Batz",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Kali",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Kukulcan",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Odin",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Ra",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Sobek",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Vamana",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Ymir",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Zeus",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Bakasura",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Anhur",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Cupid",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Thor",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Ares",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Freya",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Loki",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Bacchus",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Xbalanque",
        "against": 50,
        "teammate": 50
    }]
}, {
    "name": "Kali",
    "data": {
        "stages": ["early", "mid", "late"],
        "damageType": "magical",
        "meta": 2.5
    },
    "roles": {
        "carry": 3,
        "support": 1,
        "mid": 1,
        "jungle": 5,
        "solo": 2.5
    },
    "matchups": [{
        "god": "Agni",
        "against": 50,
        "teammate": 55
    }, {
        "god": "Anubis",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Arachne",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Artemis",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Bastet",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Hades",
        "against": 50,
        "teammate": 50
    }, {
        "god": "He Bo",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Hel",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Hun Batz",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Kali",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Kukulcan",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Odin",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Ra",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Sobek",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Vamana",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Ymir",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Zeus",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Bakasura",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Anhur",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Cupid",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Thor",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Ares",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Freya",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Loki",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Bacchus",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Xbalanque",
        "against": 50,
        "teammate": 50
    }]
}, {
    "name": "Kukulcan",
    "data": {
        "stages": ["early", "mid", "late"],
        "damageType": "magical",
        "meta": 3.5
    },
    "roles": {
        "carry": 2.5,
        "support": 1,
        "mid": 5,
        "jungle": 1,
        "solo": 1
    },
    "matchups": [{
        "god": "Agni",
        "against": 50,
        "teammate": 20
    }, {
        "god": "Anubis",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Arachne",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Artemis",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Bastet",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Hades",
        "against": 50,
        "teammate": 50
    }, {
        "god": "He Bo",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Hel",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Hun Batz",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Kali",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Kukulcan",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Odin",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Ra",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Sobek",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Vamana",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Ymir",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Zeus",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Bakasura",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Anhur",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Cupid",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Thor",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Ares",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Freya",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Loki",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Bacchus",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Xbalanque",
        "against": 50,
        "teammate": 50
    }]
}, {
    "name": "Odin",
    "data": {
        "stages": ["early", "mid", "late"],
        "damageType": "magical",
        "meta": 2
    },
    "roles": {
        "carry": 1,
        "support": 3,
        "mid": 1,
        "jungle": 3,
        "solo": 4
    },
    "matchups": [{
        "god": "Agni",
        "against": 70,
        "teammate": 55
    }, {
        "god": "Anubis",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Arachne",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Artemis",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Bastet",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Hades",
        "against": 50,
        "teammate": 50
    }, {
        "god": "He Bo",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Hel",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Hun Batz",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Kali",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Kukulcan",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Odin",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Ra",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Sobek",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Vamana",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Ymir",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Zeus",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Bakasura",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Anhur",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Cupid",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Thor",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Ares",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Freya",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Loki",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Bacchus",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Xbalanque",
        "against": 50,
        "teammate": 50
    }]
}, {
    "name": "Ra",
    "data": {
        "stages": ["early", "mid", "late"],
        "damageType": "magical",
        "meta": 2.5
    },
    "roles": {
        "carry": 1.5,
        "support": 1,
        "mid": 5,
        "jungle": 1,
        "solo": 2.5
    },
    "matchups": [{
        "god": "Agni",
        "against": 60,
        "teammate": 30
    }, {
        "god": "Anubis",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Arachne",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Artemis",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Bastet",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Hades",
        "against": 50,
        "teammate": 50
    }, {
        "god": "He Bo",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Hel",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Hun Batz",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Kali",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Kukulcan",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Odin",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Ra",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Sobek",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Vamana",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Ymir",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Zeus",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Bakasura",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Anhur",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Cupid",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Thor",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Ares",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Freya",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Loki",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Bacchus",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Xbalanque",
        "against": 50,
        "teammate": 50
    }]
}, {
    "name": "Sobek",
    "data": {
        "stages": ["early", "mid", "late"],
        "damageType": "magical",
        "meta": 3
    },
    "roles": {
        "carry": 1,
        "support": 5,
        "mid": 1,
        "jungle": 1,
        "solo": 4
    },
    "matchups": [{
        "god": "Agni",
        "against": 70,
        "teammate": 60
    }, {
        "god": "Anubis",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Arachne",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Artemis",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Bastet",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Hades",
        "against": 50,
        "teammate": 50
    }, {
        "god": "He Bo",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Hel",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Hun Batz",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Kali",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Kukulcan",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Odin",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Ra",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Sobek",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Vamana",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Ymir",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Zeus",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Bakasura",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Anhur",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Cupid",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Thor",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Ares",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Freya",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Loki",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Bacchus",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Xbalanque",
        "against": 50,
        "teammate": 50
    }]
}, {
    "name": "Vamana",
    "data": {
        "stages": ["early", "mid", "late"],
        "damageType": "magical",
        "meta": 3.5
    },
    "roles": {
        "carry": 3,
        "support": 1,
        "mid": 1,
        "jungle": 3,
        "solo": 5
    },
    "matchups": [{
        "god": "Agni",
        "against": 75,
        "teammate": 55
    }, {
        "god": "Anubis",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Arachne",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Artemis",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Bastet",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Hades",
        "against": 50,
        "teammate": 50
    }, {
        "god": "He Bo",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Hel",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Hun Batz",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Kali",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Kukulcan",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Odin",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Ra",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Sobek",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Vamana",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Ymir",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Zeus",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Bakasura",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Anhur",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Cupid",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Thor",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Ares",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Freya",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Loki",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Bacchus",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Xbalanque",
        "against": 50,
        "teammate": 50
    }]
}, {
    "name": "Ymir",
    "data": {
        "stages": ["early", "mid", "late"],
        "damageType": "magical",
        "meta": 1.5
    },
    "roles": {
        "carry": 1,
        "support": 5,
        "mid": 1,
        "jungle": 3,
        "solo": 3
    },
    "matchups": [{
        "god": "Agni",
        "against": 60,
        "teammate": 50
    }, {
        "god": "Anubis",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Arachne",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Artemis",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Bastet",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Hades",
        "against": 50,
        "teammate": 50
    }, {
        "god": "He Bo",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Hel",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Hun Batz",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Kali",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Kukulcan",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Odin",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Ra",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Sobek",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Vamana",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Ymir",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Zeus",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Bakasura",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Anhur",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Cupid",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Thor",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Ares",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Freya",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Loki",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Bacchus",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Xbalanque",
        "against": 50,
        "teammate": 50
    }]
}, {
    "name": "Zeus",
    "data": {
        "stages": ["early", "mid", "late"],
        "damageType": "magical",
        "meta": 2.5
    },
    "roles": {
        "carry": 1,
        "support": 1,
        "mid": 5,
        "jungle": 1,
        "solo": 1
    },
    "matchups": [{
        "god": "Agni",
        "against": 40,
        "teammate": 30
    }, {
        "god": "Anubis",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Arachne",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Artemis",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Bastet",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Hades",
        "against": 50,
        "teammate": 50
    }, {
        "god": "He Bo",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Hel",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Hun Batz",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Kali",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Kukulcan",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Odin",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Ra",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Sobek",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Vamana",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Ymir",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Zeus",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Bakasura",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Anhur",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Cupid",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Thor",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Ares",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Freya",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Loki",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Bacchus",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Xbalanque",
        "against": 50,
        "teammate": 50
    }]
}, {
    "name": "Bakasura",
    "data": {
        "stages": ["early", "mid", "late"],
        "damageType": "magical",
        "meta": 4
    },
    "roles": {
        "carry": 2.5,
        "support": 1,
        "mid": 1,
        "jungle": 4.5,
        "solo": 4
    },
    "matchups": [{
        "god": "Agni",
        "against": 50,
        "teammate": 60
    }, {
        "god": "Anubis",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Arachne",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Artemis",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Bastet",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Hades",
        "against": 50,
        "teammate": 50
    }, {
        "god": "He Bo",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Hel",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Hun Batz",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Kali",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Kukulcan",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Odin",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Ra",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Sobek",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Vamana",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Ymir",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Zeus",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Bakasura",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Anhur",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Cupid",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Thor",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Ares",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Freya",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Loki",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Bacchus",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Xbalanque",
        "against": 50,
        "teammate": 50
    }]
}, {
    "name": "Anhur",
    "data": {
        "stages": ["early", "mid", "late"],
        "damageType": "magical",
        "meta": 4
    },
    "roles": {
        "carry": 5,
        "support": 1,
        "mid": 4,
        "jungle": 2,
        "solo": 1
    },
    "matchups": [{
        "god": "Agni",
        "against": 70,
        "teammate": 60
    }, {
        "god": "Anubis",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Arachne",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Artemis",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Bastet",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Hades",
        "against": 50,
        "teammate": 50
    }, {
        "god": "He Bo",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Hel",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Hun Batz",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Kali",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Kukulcan",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Odin",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Ra",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Sobek",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Vamana",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Ymir",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Zeus",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Bakasura",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Anhur",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Cupid",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Thor",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Ares",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Freya",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Loki",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Bacchus",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Xbalanque",
        "against": 50,
        "teammate": 50
    }]
}, {
    "name": "Cupid",
    "data": {
        "stages": ["early", "mid", "late"],
        "damageType": "magical",
        "meta": 3
    },
    "roles": {
        "carry": 5,
        "support": 1,
        "mid": 3,
        "jungle": 1,
        "solo": 1
    },
    "matchups": [{
        "god": "Agni",
        "against": 60,
        "teammate": 60
    }, {
        "god": "Anubis",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Arachne",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Artemis",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Bastet",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Hades",
        "against": 50,
        "teammate": 50
    }, {
        "god": "He Bo",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Hel",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Hun Batz",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Kali",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Kukulcan",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Odin",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Ra",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Sobek",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Vamana",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Ymir",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Zeus",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Bakasura",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Anhur",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Cupid",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Thor",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Ares",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Freya",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Loki",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Bacchus",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Xbalanque",
        "against": 50,
        "teammate": 50
    }]
}, {
    "name": "Thor",
    "data": {
        "stages": ["early", "mid", "late"],
        "damageType": "magical",
        "meta": 4.5
    },
    "roles": {
        "carry": 2,
        "support": 2,
        "mid": 1,
        "jungle": 5,
        "solo": 3.5
    },
    "matchups": [{
        "god": "Agni",
        "against": 65,
        "teammate": 60
    }, {
        "god": "Anubis",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Arachne",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Artemis",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Bastet",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Hades",
        "against": 50,
        "teammate": 50
    }, {
        "god": "He Bo",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Hel",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Hun Batz",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Kali",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Kukulcan",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Odin",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Ra",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Sobek",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Vamana",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Ymir",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Zeus",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Bakasura",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Anhur",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Cupid",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Thor",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Ares",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Freya",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Loki",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Bacchus",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Xbalanque",
        "against": 50,
        "teammate": 50
    }]
}, {
    "name": "Ares",
    "data": {
        "stages": ["early", "mid", "late"],
        "damageType": "magical",
        "meta": 3
    },
    "roles": {
        "carry": 1,
        "support": 5,
        "mid": 1,
        "jungle": 2,
        "solo": 2
    },
    "matchups": [{
        "god": "Agni",
        "against": 65,
        "teammate": 55
    }, {
        "god": "Anubis",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Arachne",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Artemis",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Bastet",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Hades",
        "against": 50,
        "teammate": 50
    }, {
        "god": "He Bo",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Hel",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Hun Batz",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Kali",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Kukulcan",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Odin",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Ra",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Sobek",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Vamana",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Ymir",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Zeus",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Bakasura",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Anhur",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Cupid",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Thor",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Ares",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Freya",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Loki",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Bacchus",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Xbalanque",
        "against": 50,
        "teammate": 50
    }]
}, {
    "name": "Freya",
    "data": {
        "stages": ["early", "mid", "late"],
        "damageType": "magical",
        "meta": 4.5
    },
    "roles": {
        "carry": 5,
        "support": 1,
        "mid": 2,
        "jungle": 3,
        "solo": 2
    },
    "matchups": [{
        "god": "Agni",
        "against": 30,
        "teammate": 60
    }, {
        "god": "Anubis",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Arachne",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Artemis",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Bastet",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Hades",
        "against": 50,
        "teammate": 50
    }, {
        "god": "He Bo",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Hel",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Hun Batz",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Kali",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Kukulcan",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Odin",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Ra",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Sobek",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Vamana",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Ymir",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Zeus",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Bakasura",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Anhur",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Cupid",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Thor",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Ares",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Freya",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Loki",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Bacchus",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Xbalanque",
        "against": 50,
        "teammate": 50
    }]
}, {
    "name": "Loki",
    "data": {
        "stages": ["early", "mid", "late"],
        "damageType": "magical",
        "meta": 2.5
    },
    "roles": {
        "carry": 3,
        "support": 1,
        "mid": 2,
        "jungle": 3,
        "solo": 4
    },
    "matchups": [{
        "god": "Agni",
        "against": 60,
        "teammate": 50
    }, {
        "god": "Anubis",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Arachne",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Artemis",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Bastet",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Hades",
        "against": 50,
        "teammate": 50
    }, {
        "god": "He Bo",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Hel",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Hun Batz",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Kali",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Kukulcan",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Odin",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Ra",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Sobek",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Vamana",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Ymir",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Zeus",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Bakasura",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Anhur",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Cupid",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Thor",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Ares",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Freya",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Loki",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Bacchus",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Xbalanque",
        "against": 50,
        "teammate": 50
    }]
}, {
    "name": "Bacchus",
    "data": {
        "stages": ["early", "mid", "late"],
        "damageType": "magical",
        "meta": 3
    },
    "roles": {
        "carry": 1,
        "support": 5,
        "mid": 1,
        "jungle": 2,
        "solo": 1
    },
    "matchups": [{
        "god": "Agni",
        "against": 55,
        "teammate": 40
    }, {
        "god": "Anubis",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Arachne",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Artemis",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Bastet",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Hades",
        "against": 50,
        "teammate": 50
    }, {
        "god": "He Bo",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Hel",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Hun Batz",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Kali",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Kukulcan",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Odin",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Ra",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Sobek",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Vamana",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Ymir",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Zeus",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Bakasura",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Anhur",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Cupid",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Thor",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Ares",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Freya",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Loki",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Bacchus",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Xbalanque",
        "against": 50,
        "teammate": 50
    }]
}, {
    "name": "Xbalanque",
    "data": {
        "stages": ["early", "mid", "late"],
        "damageType": "magical",
        "meta": 2
    },
    "roles": {
        "carry": 5,
        "support": 1,
        "mid": 2,
        "jungle": 1,
        "solo": 1
    },
    "matchups": [{
        "god": "Agni",
        "against": 55,
        "teammate": 50
    }, {
        "god": "Anubis",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Arachne",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Artemis",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Bastet",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Hades",
        "against": 50,
        "teammate": 50
    }, {
        "god": "He Bo",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Hel",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Hun Batz",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Kali",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Kukulcan",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Odin",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Ra",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Sobek",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Vamana",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Ymir",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Zeus",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Bakasura",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Anhur",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Cupid",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Thor",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Ares",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Freya",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Loki",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Bacchus",
        "against": 50,
        "teammate": 50
    }, {
        "god": "Xbalanque",
        "against": 50,
        "teammate": 50
    }]
}]